feat(backend): update orm entities
openscript-ch/quassel pull request #117
Opened 2024-10-18 08:31 UTC by stampaaaron

2024-10-20 13:46 UTC, openscript requested changes
Great initial work!

I suggest the following changes:

- [x] Update accordingly to the most recent ERD
- [x] Fix the typos
- [ ] Add check constraints like mentioned in the ERD
- [ ] Clean up the migration: It seems like it depends on a previous migration, that is now missing. The migration doesn't run on my device.

2024-10-20 13:46 UTC, openscript commented on apps/backend/mikro-orm.config.ts
> +  host: "db",
This needs to be read from environment variables. The current values can be used as a fallback.

2024-10-20 13:46 UTC, openscript commented on apps/backend/src/entities/entry.entity.ts
> +  weekday!: number;
Add [check constraint](https://mikro-orm.io/docs/decorators#check)

2024-10-20 13:46 UTC, openscript commented on apps/backend/src/entities/entry.entity.ts
> +  questionnarie!: Questionnaire;
Typo

2024-10-20 13:46 UTC, openscript commented on apps/backend/src/entities/entryLanguage.entity.ts
> +  ration!: string;
Typo

2024-10-21 06:59 UTC, stampaaaron commented on apps/backend/mikro-orm.config.ts
> +  host: "db",
This will be added with the next PR: https://github.com/openscript-ch/quassel/pull/118/files#diff-8729413cb547fea83d4cb119a40679dc442517ce5b2cc2d1eeb77af51aa8991fR9

2024-10-21 06:59 UTC, stampaaaron commented on apps/backend/src/entities/entry.entity.ts
> +  weekday!: number;
Nice idea!

2024-10-21 07:14 UTC, openscript commented on apps/backend/mikro-orm.config.ts
> +  host: "db",
Perfect :)

2024-10-24 07:10 UTC, openscript approved these changes

2024-10-24 07:12 UTC, merged